[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gem-llm"
dynamic = ["version"]
description = 'A Gym for Generalist LLMs.'
readme = "README.md"
requires-python = ">=3.10"
keywords = []
authors = [
  { name = "Zichen Liu", email = "lkevinzc@gmail.com" },
  { name = "Anya Sims", email = "anya.sims@stats.ox.ac.uk" },
  { name = "Keyu Duan", email = "k.duan@u.nus.edu" },
  { name = "Changyu Chen", email = "abelco.cy@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "nltk==3.9.1",
  "math-verify[antlr4_13_2]",
  "reasoning-gym==0.1.23",
]

[project.optional-dependencies]
search = [
  "msgspec",
  "mosec",
  "aiohttp",
  "bs4",
  "chardet",
  "google-api-python-client",
  "torch",
  "torchvision",
  "torchaudio",
  "transformers",
  "datasets",
  "pyserini",
]

[project.urls]
Documentation = "https://axon-rl.github.io/gem/"
Issues = "https://github.com/axon-rl/gem/issues"
Source = "https://github.com/axon-rl/gem"

[project.license]
text = "Apache-2.0"

[tool.hatch.version]
path = "gem/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:gem tests}"

[tool.coverage.run]
source_pkgs = ["gem", "tests"]
branch = true
parallel = true
omit = [
  "gem/__about__.py",
]

[tool.coverage.paths]
gem = ["gem", "*/gem/gem"]
tests = ["tests", "*/gem/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.uv.sources]
reasoning-gym = { git = "https://github.com/open-thought/reasoning-gym", rev = "1c98584" }
