blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://axon-rl.github.io/gem/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/axon-rl/gem/discussions/new/choose
    about: Ask a question or start a discussion
  - name: Chat on Discord
    url: https://discord.gg/AfXVkEphzD
    about: Maybe chatting with the community can help
